<?php

function icg_csv_import_menu() {
  $items = array();
  $items['islandora/object/%islandora_object/manage/csv-import'] = array(
      'title' => t('CSV Import'),
      'page callback' => 'icg_csv_import_form',
      'page arguments' => array(2),
      'access arguments' => array(2),
      'access callback' => 'icg_csv_access_callback',
      'type' => MENU_LOCAL_TASK,
      'file' => 'map_ingest_form.inc',	 // don't forget to add the file and path
      'file path' => drupal_get_path('icg_csv_import', 'includes'),
  );
  return $items;
}

/**
 * ICG CSV Menu Item Access Callback
 */
function icg_csv_access_callback($object) {
  dpm('here');
  if (user_access('ingest fedora objects')) {
    $relation = '';
    $collection_models = islandora_basic_collection_get_collection_content_models();
    $collection_predicates = array(
      'isMemberOfCollection',
      'isMemberOf',
    );
    $is_a_collection = (
      (count(array_intersect($collection_models, $object->models)) > 0) &&
      isset($object['COLLECTION_POLICY']) &&
      (count(array_intersect($collection_predicates, array($relation))) > 0)
    );
    return $is_a_collection;
  }
  return FALSE;
}

