<?php

/**
 * $headers: An array of xpaths of field destinations
 * $row: A corresponding list of data to deliver to those destinations
 * $xml_form_id: TBD, but some sort of identifier for the form sending the data
 * $parent_object:
 * $namespace: To place the objects into
 * $ingest_as_inactive: Whether to flag all ingested objects as inactive
 *
 * Result: an ingested Fedora object`
 * Error handling: return PID
 */

 function icg_csv_import_batch_item($headers, $row, $xml_form_id, $parent_object, $namespace, $ingest_as_inactive) {

   // return
 }
